### ISSUE TITLE
A website that may be helpful, suggest to read

### ISSUE THREAD

**Issue by Lancasterwu** [Allegheny-Computer-Science-203-S2019/cs203-S2019-assessment#1]
https://www.software.ac.uk/resources/guides-everything/software-evaluation-guide

**Comment by Lancasterwu** [comment]
any comments?

**Comment by gkapfham** [comment]
Hello @Lancasterwu, I encourage you to reach out to your colleagues in the course so that they will give you feedback on this issue.

**Comment by Lancasterwu** [comment]
Hi @gkapfham 
I shared the link of this issue to the slack last week. However, it seems like people aren't familiar to the use of issues on Github
