### ISSUE TITLE
Edit  Professional Skills Individual, Group, Iteractions & Revision of Guides

### ISSUE THREAD

**Issue by Lancasterwu** [Allegheny-Computer-Science-203-S2019/cs203-S2019-assessment#2]
group leader: @huangs1
team 1 member: @Lancasterwu  @libailong  @mmarconi @huangs1
team 2 member: @everitt-andrew @ALEXANDERB82 @leonardoz15 @reibelj (JohnathanReibel)

**Comment by Lancasterwu** [comment]
The fork we are working on:
https://github.com/huangs1/assessment-professional-groupandinteractions

**Comment by Lancasterwu** [comment]
@khanm Finished Group & Iteractions for Professional Skills category, please review and check if it is ok to merge.

**Comment by Lancasterwu** [comment]
Process update: Merging the "Individual" & "revision of guides" to the professional skill category
Still need to fix some bugs
https://github.com/huangs1/assessment-professional-skills/pull/6

**Comment by Lancasterwu** [comment]
Finished. Ready to be merged in to the main.
#4

**Comment by gkapfham** [comment]
Hello @Lancasterwu, do you think that you should be creating a pull request for this? What is your status? Please make sure that your work is finished and ready to be merged into the master branch of the repository.

**Comment by Lancasterwu** [comment]
Hi @gkapfham. We made a little bit more updates like changing grammar errors. 
Our team leader @huangs1 just made another pull request
#7

**Comment by Lancasterwu** [comment]
Finished
